# Generated by Django 3.2.4 on 2021-06-24 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chronicle',
            name='status',
            field=models.SmallIntegerField(choices=[(1, 'Open'), (2, 'Closed')], default=1),
        ),
    ]
